"""empty message

Revision ID: dee6f48a3c9f
Revises: 8f730b903d14
Create Date: 2025-01-29 16:22:45.713821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee6f48a3c9f'
down_revision = '8f730b903d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_events_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])
        batch_op.drop_column('events_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_events_id_fkey', 'events', ['events_id'], ['id'])
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
